
security.user:
    name: user
    password: user

spring:
    h2.console.enabled: true

    jpa:
        hibernate.ddl-auto: create
        show-sql: false

    datasource:
        url: jdbc:h2:/work/db/dbTest;AUTO_SERVER=TRUE
        username: test
        password: test
        driver-class-name: org.h2.Driver

    data.rest.base-path: /rest

    main.web-environment: false

onlineShop.strategies.quantityStrategyType: MOSTABUNDANT
